### PR TITLE
Trials

### PR DESCRIPTION
**Pull request by MrPickles**
This PR allows writes of trial data to private sheets.

API changes:
* new contructor `Sheets(Host host, String appName, String spreadsheetId, String privateSpreadsheetId)` (new parameter for private sheet id)
* `writeTrials (TestType testType, String userId, float[] trials)` method
* `HEAD_SWAY` enum for new app

There's also an updated sample.

### CODE REVIEW

**Comment by MrPickles** [comment]
fixes #3

**Review by krockpot — APPROVED** [review]
Great work.

**Comment by krockpot** [comment]
Personally, I think adding back-to-back query support would be beneficial.

**Comment by MrPickles** [comment]
@krockpot `writeData` and `writeTrials` calls don't have to be handled by user callbacks. You can now call them back to back without worrying about asynchronous issues.

**Comment by 0queue** [comment]
Just a heads up, I am noticing a lot of casting the Host to Activity in the code.  There are no guarantees that Host is an Activity, and as such the Activity should be passed in as a separate parameter or similar.

**Comment by MrPickles** [comment]
@0queue I thought we talked about this before. The consensus was that we'd assume that the host would be an activity, rather than a fragment or something similar. I'm against an interface that requires the user to just `return this`.

Do you know if there's any way to enforce an interface to have it such that the implementing class is an activity of some sort? I don't know of such a method. Maybe an abstract class that extends activity and implements the host, but that seems messy.

A more realistic alternative would be to add another parameter to the constructor that is of type activity. The constructor invocation would look something like

```java
Sheets sheet = new Sheets(this, this, ...);
```

which seems unwieldy but is best for safety.

Anyway, let me know your thoughts. I want to get this merged and released soon so other groups aren't waiting for too long.

**Comment by 0queue** [comment]
Right, we agreed it didn't belong in the interface, but we still need an Activity, and it makes more sense as a parameter to the Sheets constructor.

**Comment by MrPickles** [comment]
Okay, the new constructor takes two parameters that will probably be `this`. I was thinking about making the activity parameter optional and have multiple supported constructors, but since there's the API change with the private spreadsheet, I'd might as well enforce it such that everybody uses the same singular constructor.

**Pull request merged**
